(export (version D)
  (source "src/oams_valve_driver.sch")
  (date "2026-09-15 15:02:44")
  (tool "Eeschema (6.0.0-rc1)")
  (components
    (comp (ref IC_GATE01)
      (value "16State_Analog_Comparator")
      (footprint "RT_Footprints:Hex_Logic_SOIC-16")
      (libsource (lib "RT_Avionics") (part "Hex_Comparator") (description "16-State Window Discriminator Logic Gate"))
      (sheetpath (names "/") (tstamps "/"))
      (tstamp "61BC3A12"))
    (comp (ref Q_MOS01)
      (value "GaN_Power_Switch_N_Channel")
      (footprint "RT_Footprints:GaN_HighPower_SMD")
      (libsource (lib "RT_Power") (part "GaN_FET") (description "Gallium Nitride Fast-Switching Power Transistor"))
      (sheetpath (names "/") (tstamps "/"))
      (tstamp "61BD4E8F"))
    (comp (ref D_FLY01)
      (value "Schottky_Flyback_Diode")
      (footprint "RT_Footprints:Diode_DO-214AC")
      (libsource (lib "Device") (part "D_Schottky") (description "Schottky Flyback Diode for Solenoid Inductive Suppression"))
      (sheetpath (names "/") (tstamps "/"))
      (tstamp "61BE6C04")))
  (nets
    (net (code 1) (name "/PROP_W_1")
      (node (ref IC_GATE01) (pin 3))
      (comment "16-State Cymatic Wave Guide Reference input Voltage Trace"))
    (net (code 2) (name "/GATE_DRIVE_PWM")
      (node (ref IC_GATE01) (pin 8))
      (node (ref Q_MOS01) (pin 1))
      (comment "High-Speed Gating Output Pin running to GaN Power FET"))
    (net (code 3) (name "/THRUSTER_SOLENOID_LOW")
      (node (ref Q_MOS01) (pin 2))
      (node (ref D_FLY01) (pin 1))
      (comment "Switched Low-Side Valve Controller Line Running Outside Hull"))
    (net (code 4) (name "+28V_THRUSTER_BUS")
      (node (ref D_FLY01) (pin 2))
      (comment "Isolated Main High-Power Propulsion Supply Voltage Trace"))
    (net (code 5) (name "GND")
      (node (ref IC_GATE01) (pin 16))
      (node (ref Q_MOS01) (pin 3)))
)
